"""add unique constraint to categories

Revision ID: 10b3125e19cb
Revises: 4e18b1460a1d
Create Date: 2026-08-13 16:00:00.211249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10b3125e19cb'
down_revision: Union[str, Sequence[str], None] = '4e18b1460a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
