"""add destination account to transactions

Revision ID: 53b1eda660c8
Revises: a3e31e31ba83
Create Date: 2026-08-14 14:22:11.708063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b1eda660c8'
down_revision: Union[str, Sequence[str], None] = 'a3e31e31ba83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('destination_account_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('transactions_category_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['destination_account_id'], ['id'])
    op.drop_column('transactions', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_category_id_fkey'), 'transactions', 'categories', ['category_id'], ['id'])
    op.drop_column('transactions', 'destination_account_id')
    # ### end Alembic commands ###
